# Generated by Django 5.2.7 on 2025-11-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonquery',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisonquery',
            name='verdict',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guidelinedocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuidelineChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='guidelines.guidelinedocument')),
            ],
        ),
    ]
