# Generated by Django 5.2.7 on 2025-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='emotion_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
