# Generated by Django 5.2.7 on 2025-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_emotion_justification_journalentry_model_result_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='emotion_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
