# Generated by Django 5.2.7 on 2025-11-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('analyzed_summary', models.TextField(blank=True, null=True)),
                ('findings_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
